# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/User2/Desktop/VivadoProjects/TDLA-i7server/Tproc/Tproclocal/Tproclocal.srcs/sources_1/ip/var_len_shift_ram/var_len_shift_ram.xci
# IP: The module: 'var_len_shift_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User2/Desktop/VivadoProjects/TDLA-i7server/Tproc/Tproclocal/Tproclocal.srcs/sources_1/ip/var_len_shift_ram/var_len_shift_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'var_len_shift_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/User2/Desktop/VivadoProjects/TDLA-i7server/Tproc/Tproclocal/Tproclocal.srcs/sources_1/ip/var_len_shift_ram/var_len_shift_ram.xci
# IP: The module: 'var_len_shift_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/User2/Desktop/VivadoProjects/TDLA-i7server/Tproc/Tproclocal/Tproclocal.srcs/sources_1/ip/var_len_shift_ram/var_len_shift_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'var_len_shift_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
