# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gigabyte/workspace/Tproc_local/Tproc/Tproclocal/Tproclocal.srcs/sources_1/ip/asymmetric_fifo/asymmetric_fifo.xci
# IP: The module: 'asymmetric_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gigabyte/workspace/Tproc_local/Tproc/Tproclocal/Tproclocal.srcs/sources_1/ip/asymmetric_fifo/asymmetric_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'asymmetric_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/gigabyte/workspace/Tproc_local/Tproc/Tproclocal/Tproclocal.srcs/sources_1/ip/asymmetric_fifo/asymmetric_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'asymmetric_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/gigabyte/workspace/Tproc_local/Tproc/Tproclocal/Tproclocal.srcs/sources_1/ip/asymmetric_fifo/asymmetric_fifo.xci
# IP: The module: 'asymmetric_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gigabyte/workspace/Tproc_local/Tproc/Tproclocal/Tproclocal.srcs/sources_1/ip/asymmetric_fifo/asymmetric_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'asymmetric_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/gigabyte/workspace/Tproc_local/Tproc/Tproclocal/Tproclocal.srcs/sources_1/ip/asymmetric_fifo/asymmetric_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'asymmetric_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
